"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-20 14:51:33.297923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('symbol'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('job_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('git_commit', sa.String(length=40), nullable=True),
    sa.Column('git_dirty', sa.Boolean(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('trading_days',
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('trade_date'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ohlcv_daily',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['job_runs.id'], ),
    sa.ForeignKeyConstraint(['symbol'], ['instruments.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'trade_date'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('universe_membership',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('universe_code', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['instruments.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('universe_code', 'symbol', 'effective_from', name='uq_membership'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_membership_lookup', 'universe_membership', ['universe_code', 'effective_from', 'effective_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_membership_lookup', table_name='universe_membership')
    op.drop_table('universe_membership')
    op.drop_table('ohlcv_daily')
    op.drop_table('trading_days')
    op.drop_table('job_runs')
    op.drop_table('instruments')
    # ### end Alembic commands ###
