"""data layer: quality findings, intraday bars, ingest run status

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-20 16:18:14.289913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_known_issues',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('issue_key', sa.String(length=64), nullable=False),
    sa.Column('check_name', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('treatment', sa.String(length=48), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(UTC_TIMESTAMP())'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_key'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('data_quality_findings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('check_name', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('subject_key', sa.String(length=10), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('known_issue_id', sa.BigInteger(), nullable=True),
    sa.Column('first_seen_run_id', sa.BigInteger(), nullable=True),
    sa.Column('last_seen_run_id', sa.BigInteger(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('(UTC_TIMESTAMP())'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(UTC_TIMESTAMP())'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['first_seen_run_id'], ['job_runs.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['known_issue_id'], ['data_quality_known_issues.id'], ),
    sa.ForeignKeyConstraint(['last_seen_run_id'], ['job_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'check_name', 'subject_key', name='uq_dq_finding'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_dq_status', 'data_quality_findings', ['status', 'severity'], unique=False)
    op.create_table('price_bar_intraday',
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('resolution', sa.String(length=4), nullable=False),
    sa.Column('bar_time', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('price_basis', sa.String(length=16), server_default='vendor_adjusted', nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['job_runs.id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'resolution', 'bar_time'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.add_column('corporate_actions', sa.Column('status', sa.String(length=12), server_default='confirmed', nullable=False))
    op.create_unique_constraint('uq_corporate_action', 'corporate_actions', ['instrument_id', 'ex_date', 'action_type'])
    op.add_column('data_ingest_runs', sa.Column('resolution', sa.String(length=4), server_default='1D', nullable=False))
    op.add_column('data_ingest_runs', sa.Column('status', sa.String(length=10), server_default='ok', nullable=False))
    op.add_column('data_ingest_runs', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('data_ingest_runs', sa.Column('params', sa.JSON(), nullable=True))
    op.add_column('data_ingest_runs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_ingest_runs', 'duration_ms')
    op.drop_column('data_ingest_runs', 'params')
    op.drop_column('data_ingest_runs', 'error')
    op.drop_column('data_ingest_runs', 'status')
    op.drop_column('data_ingest_runs', 'resolution')
    op.drop_constraint('uq_corporate_action', 'corporate_actions', type_='unique')
    op.drop_column('corporate_actions', 'status')
    op.drop_table('price_bar_intraday')
    op.drop_index('ix_dq_status', table_name='data_quality_findings')
    op.drop_table('data_quality_findings')
    op.drop_table('data_quality_known_issues')
    # ### end Alembic commands ###
